using System;
using System.Collections.Generic;

namespace pdc.Models.T543
{
    public partial class DaiodaM
    {
        public string? DaiLine { get; set; }
        public string? DaiDaio { get; set; }
        public string? DaiOdai { get; set; }
        public string? DaiName { get; set; }
        public string? DaiModl { get; set; }
        public string? DaiHpfg { get; set; }
        public string? DaiNafg { get; set; }
        public string? DaiLdhd { get; set; }
        public string? DaiToud { get; set; }
        public string? DaiForm { get; set; }
        public string? DaiNlbc { get; set; }
        public string? DaiOlbc { get; set; }
        public string? DaiNbsu { get; set; }
        public string? DaiObsu { get; set; }
        public string? DaiNplb { get; set; }
        public string? DaiOplb { get; set; }
        public string? DaiLstf { get; set; }
        public string? DaiItfp { get; set; }
        public string? DaiItfd { get; set; }
        public string? DaiNdtp { get; set; }
        public string? DaiOdtp { get; set; }
        public string? DaiNmip { get; set; }
        public string? DaiOmip { get; set; }
        public string? DaiRsv1 { get; set; }
        public string? DaiRsv2 { get; set; }
        public string? DaiUns1 { get; set; }
        public string? DaiUnj1 { get; set; }
        public string? DaiUpt1 { get; set; }
        public string? DaiHpd1 { get; set; }
        public string? DaiUns2 { get; set; }
        public string? DaiUnj2 { get; set; }
        public string? DaiUpt2 { get; set; }
        public string? DaiHpd2 { get; set; }
        public string? DaiUns3 { get; set; }
        public string? DaiUnj3 { get; set; }
        public string? DaiUpt3 { get; set; }
        public string? DaiHpd3 { get; set; }
        public string? DaiUns4 { get; set; }
        public string? DaiUnj4 { get; set; }
        public string? DaiUpt4 { get; set; }
        public string? DaiHpd4 { get; set; }
        public string? DaiUns5 { get; set; }
        public string? DaiUnj5 { get; set; }
        public string? DaiUpt5 { get; set; }
        public string? DaiHpd5 { get; set; }
        public string? DaiUns6 { get; set; }
        public string? DaiUnj6 { get; set; }
        public string? DaiUpt6 { get; set; }
        public string? DaiHpd6 { get; set; }
        public string? DaiUns7 { get; set; }
        public string? DaiUnj7 { get; set; }
        public string? DaiUpt7 { get; set; }
        public string? DaiHpd7 { get; set; }
        public string? DaiUns8 { get; set; }
        public string? DaiUnj8 { get; set; }
        public string? DaiUpt8 { get; set; }
        public string? DaiHpd8 { get; set; }
        public string? DaiUns9 { get; set; }
        public string? DaiUnj9 { get; set; }
        public string? DaiUpt9 { get; set; }
        public string? DaiHpd9 { get; set; }
        public string? DaiUnsa { get; set; }
        public string? DaiUnja { get; set; }
        public string? DaiUpta { get; set; }
        public string? DaiHpda { get; set; }
        public string? DaiUnsb { get; set; }
        public string? DaiUnjb { get; set; }
        public string? DaiUptb { get; set; }
        public string? DaiHpdb { get; set; }
        public string? DaiUnsc { get; set; }
        public string? DaiUnjc { get; set; }
        public string? DaiUptc { get; set; }
        public string? DaiHpdc { get; set; }
        public string? DaiUnsd { get; set; }
        public string? DaiUnjd { get; set; }
        public string? DaiUptd { get; set; }
        public string? DaiHpdd { get; set; }
        public string? DaiUnse { get; set; }
        public string? DaiUnje { get; set; }
        public string? DaiUpte { get; set; }
        public string? DaiHpde { get; set; }
        public string? DaiUnsf { get; set; }
        public string? DaiUnjf { get; set; }
        public string? DaiUptf { get; set; }
        public string? DaiHpdf { get; set; }
        public string? DaiUnsg { get; set; }
        public string? DaiUnjg { get; set; }
        public string? DaiUptg { get; set; }
        public string? DaiHpdg { get; set; }
        public string? DaiUnsh { get; set; }
        public string? DaiUnjh { get; set; }
        public string? DaiUpth { get; set; }
        public string? DaiHpdh { get; set; }
        public string? DaiUnsi { get; set; }
        public string? DaiUnji { get; set; }
        public string? DaiUpti { get; set; }
        public string? DaiHpdi { get; set; }
        public string? DaiUnsj { get; set; }
        public string? DaiUnjj { get; set; }
        public string? DaiUptj { get; set; }
        public string? DaiHpdj { get; set; }
        public string? DaiUnsk { get; set; }
        public string? DaiUnjk { get; set; }
        public string? DaiUptk { get; set; }
        public string? DaiHpdk { get; set; }
        public string? DaiBms1 { get; set; }
        public string? DaiBmj1 { get; set; }
        public string? DaiBmp1 { get; set; }
        public string? DaiBms2 { get; set; }
        public string? DaiBmj2 { get; set; }
        public string? DaiBmp2 { get; set; }
        public string? DaiBms3 { get; set; }
        public string? DaiBmj3 { get; set; }
        public string? DaiBmp3 { get; set; }
        public string? DaiBms4 { get; set; }
        public string? DaiBmj4 { get; set; }
        public string? DaiBmp4 { get; set; }
        public string? DaiBms5 { get; set; }
        public string? DaiBmj5 { get; set; }
        public string? DaiBmp5 { get; set; }
        public string? DaiBms6 { get; set; }
        public string? DaiBmj6 { get; set; }
        public string? DaiBmp6 { get; set; }
        public string? DaiBms7 { get; set; }
        public string? DaiBmj7 { get; set; }
        public string? DaiBmp7 { get; set; }
        public string? DaiBms8 { get; set; }
        public string? DaiBmj8 { get; set; }
        public string? DaiBmp8 { get; set; }
        public string? DaiBms9 { get; set; }
        public string? DaiBmj9 { get; set; }
        public string? DaiBmp9 { get; set; }
        public string? DaiBmsa { get; set; }
        public string? DaiBmja { get; set; }
        public string? DaiBmpa { get; set; }
        public string? DaiBmsb { get; set; }
        public string? DaiBmjb { get; set; }
        public string? DaiBmpb { get; set; }
        public string? DaiBmsc { get; set; }
        public string? DaiBmjc { get; set; }
        public string? DaiBmpc { get; set; }
        public string? DaiBmsd { get; set; }
        public string? DaiBmjd { get; set; }
        public string? DaiBmpd { get; set; }
        public string? DaiBmse { get; set; }
        public string? DaiBmje { get; set; }
        public string? DaiBmpe { get; set; }
        public string? DaiBmsf { get; set; }
        public string? DaiBmjf { get; set; }
        public string? DaiBmpf { get; set; }
        public string? DaiBmsg { get; set; }
        public string? DaiBmjg { get; set; }
        public string? DaiBmpg { get; set; }
        public string? DaiBmsh { get; set; }
        public string? DaiBmjh { get; set; }
        public string? DaiBmph { get; set; }
        public string? DaiBmsi { get; set; }
        public string? DaiBmji { get; set; }
        public string? DaiBmpi { get; set; }
        public string? DaiBmsj { get; set; }
        public string? DaiBmjj { get; set; }
        public string? DaiBmpj { get; set; }
        public string? DaiBmsk { get; set; }
        public string? DaiBmjk { get; set; }
        public string? DaiBmpk { get; set; }
        public string? DaiHn1s { get; set; }
        public string? DaiHn1e { get; set; }
        public string? DaiHn2s { get; set; }
        public string? DaiHn2e { get; set; }
        public string? DaiHn3s { get; set; }
        public string? DaiHn3e { get; set; }
        public string? DaiHn4s { get; set; }
        public string? DaiHn4e { get; set; }
        public string? DaiHn5s { get; set; }
        public string? DaiHn5e { get; set; }
        public string? DaiHb1s { get; set; }
        public string? DaiHb2s { get; set; }
        public string? DaiHb3s { get; set; }
        public string? DaiHb4s { get; set; }
        public string? DaiHb5s { get; set; }
    }
}
