using System;
using System.Collections.Generic;

namespace pdc.Models.L1231
{
    public partial class JisekiF
    {
        public string? JisLine { get; set; }
        public string? JisDaio { get; set; }
        public string? JisSile { get; set; }
        public string? JisBody { get; set; }
        public string? JisIkan { get; set; }
        public string? JisToud { get; set; }
        public string? JisTout { get; set; }
        public string? JisTosd { get; set; }
        public string? JisTost { get; set; }
        public string? JisUnrd { get; set; }
        public string? JisUnrt { get; set; }
        public string? JisUnsd { get; set; }
        public string? JisUnst { get; set; }
        public string? JisUn1n { get; set; }
        public string? JisUn1h { get; set; }
        public string? JisUn2n { get; set; }
        public string? JisUn2h { get; set; }
        public string? JisUn3n { get; set; }
        public string? JisUn3h { get; set; }
        public string? JisUn4n { get; set; }
        public string? JisUn4h { get; set; }
        public string? JisUn5n { get; set; }
        public string? JisUn5h { get; set; }
        public string? JisUn6n { get; set; }
        public string? JisUn6h { get; set; }
        public string? JisUn7n { get; set; }
        public string? JisUn7h { get; set; }
        public string? JisUn8n { get; set; }
        public string? JisUn8h { get; set; }
        public string? JisUn9n { get; set; }
        public string? JisUn9h { get; set; }
        public string? JisUnan { get; set; }
        public string? JisUnah { get; set; }
        public string? JisUnbn { get; set; }
        public string? JisUnbh { get; set; }
        public string? JisUncn { get; set; }
        public string? JisUnch { get; set; }
        public string? JisUndn { get; set; }
        public string? JisUndh { get; set; }
        public string? JisUnen { get; set; }
        public string? JisUneh { get; set; }
        public string? JisUnfn { get; set; }
        public string? JisUnfh { get; set; }
        public string? JisUngn { get; set; }
        public string? JisUngh { get; set; }
        public string? JisUnhn { get; set; }
        public string? JisUnhh { get; set; }
        public string? JisUnin { get; set; }
        public string? JisUnih { get; set; }
        public string? JisUnjn { get; set; }
        public string? JisUnjh { get; set; }
        public string? JisUnkn { get; set; }
        public string? JisUnkh { get; set; }
        public string? JisMkrd { get; set; }
        public string? JisMkrt { get; set; }
        public string? JisMksd { get; set; }
        public string? JisMkst { get; set; }
        public string? JisMk1n { get; set; }
        public string? JisMk1h { get; set; }
        public string? JisMk2n { get; set; }
        public string? JisMk2h { get; set; }
        public string? JisMk3n { get; set; }
        public string? JisMk3h { get; set; }
        public string? JisMk4n { get; set; }
        public string? JisMk4h { get; set; }
        public string? JisMk5n { get; set; }
        public string? JisMk5h { get; set; }
        public string? JisMk6n { get; set; }
        public string? JisMk6h { get; set; }
        public string? JisMk7n { get; set; }
        public string? JisMk7h { get; set; }
        public string? JisMk8n { get; set; }
        public string? JisMk8h { get; set; }
        public string? JisMk9n { get; set; }
        public string? JisMk9h { get; set; }
        public string? JisMkan { get; set; }
        public string? JisMkah { get; set; }
        public string? JisMkbn { get; set; }
        public string? JisMkbh { get; set; }
        public string? JisMkcn { get; set; }
        public string? JisMkch { get; set; }
        public string? JisMkdn { get; set; }
        public string? JisMkdh { get; set; }
        public string? JisMken { get; set; }
        public string? JisMkeh { get; set; }
        public string? JisMkfn { get; set; }
        public string? JisMkfh { get; set; }
        public string? JisMkgn { get; set; }
        public string? JisMkgh { get; set; }
        public string? JisMkhn { get; set; }
        public string? JisMkhh { get; set; }
        public string? JisMkin { get; set; }
        public string? JisMkih { get; set; }
        public string? JisMkjn { get; set; }
        public string? JisMkjh { get; set; }
        public string? JisMkkn { get; set; }
        public string? JisMkkh { get; set; }
        public string? JisKoud { get; set; }
        public string? JisKout { get; set; }
        public string? JisKosd { get; set; }
        public string? JisKost { get; set; }
        public string? JisKoft { get; set; }
        public string? JisKosn { get; set; }
        public string? JisVers { get; set; }
        public string? JisKand { get; set; }
        public string? JisKant { get; set; }
        public string? JisKasd { get; set; }
        public string? JisKast { get; set; }
        public string? JisKanc { get; set; }
        public string? JisKpod { get; set; }
        public string? JisKpot { get; set; }
        public string? JisKpsd { get; set; }
        public string? JisKpst { get; set; }
        public string? JisKpoc { get; set; }
        public string? JisPlno { get; set; }
        public string? JisPlse { get; set; }
        public string? JisSsno { get; set; }
        public string? JisCano { get; set; }
        public string? JisOcar { get; set; }
        public string? JisNakd { get; set; }
        public string? JisNaks { get; set; }
        public string? JisCmnt { get; set; }
        public string? JisNetd { get; set; }
        public string? JisNeta { get; set; }
        public string? JisCono { get; set; }
        public string? JisPono { get; set; }
        public string? JisSstd { get; set; }
    }
}
